### ISSUE TITLE
Afterburner plugin - Per CPU core load/temp/clock - Null

### ISSUE THREAD

**Issue by Romainrob** [zegreatclan/SimHub#357]
Bonjour!
I can't get the per CPU core  load, temp or clock from the MSI Afterburner plugin. 
Only the CPU1 seems to work. The others are null.
All all cores info is correctly displayed in the msi monitor graph.
I tried reducing the the amount of monitored items in afterburner = same issue. 

![Afterburner Core Loads](https://user-images.githubusercontent.com/50543913/59206609-96f4c880-8ba5-11e9-9575-fa3b001ee19e.PNG)

Looking at the differences in the names, there might be a mix-up somewhere.
I'm running Afterburner 4.6.1 (up to date) and a i7-6700k.

**Comment by zegreatclan** [comment]
Fix released with 6.8.0 ;)

**Comment by danfeliix** [comment]
@SHWotever  Bet on formatting my PC and reinstalling SimHub. I am not able to make Afterburner work and stay connected.

![Captura de Tela (8) cópia](https://user-images.githubusercontent.com/54558657/80924740-0e54bd00-8d61-11ea-92c9-2f494d87962a.png)

**Comment by SHWotever** [comment]
@danfeliix you have the instructions here ;) https://github.com/SHWotever/SimHub/wiki/System-informations#afterburner-configuration

**Comment by danfeliix** [comment]
@SHWotever  Follow the instructions and still don't connect. I start Afterburner and SimHub as an administrator. I tested the Aida64 worked, but the Afterbuner didn't work

**Comment by SHWotever** [comment]
How many active monitoring are still enabled in afterburner ? I can't remember the exact number where afterburner stops sending data  but I think it's pretty low.

**Comment by danfeliix** [comment]
@SHWotever  I left the default Afterburner when I installed it, I didn't change anything
![Captura de Tela (9)](https://user-images.githubusercontent.com/54558657/80926045-f5e9a000-8d6a-11ea-86ec-07302773f17d.png)

**Comment by SHWotever** [comment]
Ah so try to remove some until it works. It's a know bug of afterburner. It wasn't an issue a few years ago but now with so many cores, temperatures and voltages you can go above the limit out of box.

**Comment by danfeliix** [comment]
@SHWotever  friend found out what it was, is that I changed the processor that now has 6-Colors 12-Threads so I increased the number of monitoring. Thanks for answering.

Taking advantage, does the solution for the names of ETS2 cities appear on the translated LCD? The SimHub standard is wonderful to read all maps in English only
